onboarding = false

[theme]
name = "one-dark"

[ui]
mouse_capture = true
redraw_on_focus_gained = true
agent_panel_scope = "all"

[keys]
prefix = "ctrl+space"
workspace_picker = "prefix+w"
settings = ""
split_horizontal = "prefix+s"
copy_mode = "prefix+0"
switch_tab = ""
focus_agent = "prefix+1..9"
next_agent = "prefix+space"
previous_agent = "prefix+tab"
rename_tab = "prefix+m"
new_tab = "prefix+t"
cycle_pane_next = ""
cycle_pane_previous = ""
navigate_pane_down = ""
navigate_pane_up = ""
navigate_workspace_up = "k"
navigate_workspace_down = "j"
previous_tab = "prefix+shift+k"
next_tab = "prefix+shift+j"
new_workspace = ""

[[keys.command]]
key = "prefix+shift+n"
type = "pane"
command = "/Users/didi/.local/bin/herdr-new-workspace"

[[keys.command]]
key = "prefix+a"
type = "pane"
command = "/Users/didi/.local/bin/herdr-switch-agent"

[[keys.command]]
key = "prefix+u"
type = "pane"
command = "/Users/didi/.local/bin/herdr-urls"

[[keys.command]]
key = "prefix+f"
type = "pane"
command = "/Users/didi/.local/bin/herdr-files"
